/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Items.Conectar;
import Items.JPanelColor;
import Pojo.UseUser;
import Pojo.Usuario;
import java.awt.Cursor;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author h p
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(this.getClass().getResource("/Imagen/capsule.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField(8);
        Chang1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField(8);
        Aceptar = new javax.swing.JButton();
        Change1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2 = new JPanelColor("/Imagen/Fondo.jpg");
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel1Layout.rowHeights = new int[] {0, 12, 0, 12, 0, 12, 0, 12, 0, 12, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        jPanel1.add(Name, gridBagConstraints);

        Chang1.setForeground(new java.awt.Color(255, 255, 255));
        Chang1.setText("Ha olvidado la contraseña?");
        Chang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Chang1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chang1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(Chang1, gridBagConstraints);

        ImageIcon im = new ImageIcon(this.getClass().getResource("/Imagen/Users.png"));
        jLabel4.setText("");
        jLabel4.setIcon(im);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        jPanel1.add(Pass, gridBagConstraints);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(Aceptar, gridBagConstraints);

        Change1.setForeground(new java.awt.Color(255, 255, 255));
        Change1.setText("Ha olvidado la contraseña?");
        Change1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Change1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Change1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(Change1, gridBagConstraints);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(402, 251));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Chang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chang1MouseClicked
        // TODO add your handling code here:
        if(flag){
            JOptionPane.showMessageDialog(null,"Pongase en contacto con: \n"
                    + "Jonagonzalez12797@yahoo.es\n"
                    + "+5058904-5974");
        }
    }//GEN-LAST:event_Chang1MouseClicked

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Usuario s = new Usuario();
        boolean band = false;
        if(flag){
            if(!(Name.getText().equals("") && Pass.getText().equals(""))){
                s.setAdministrador(true);
                s.setEmpleado(false);
                s.setName(Name.getText());
                s.setPassword(Pass.getText());
                for(Usuario us : users){
                    if(s.getName().equalsIgnoreCase(us.getName())){
                        if(s.getPassword().equals(us.getPassword())){
                            if(us.isAdministrador()){
                                ImageIcon i = new ImageIcon(this.getClass().getResource("/Imagen/Back.jpg"));
                                JOptionPane.showMessageDialog(null,"Bienvenido","Welcome",JOptionPane.INFORMATION_MESSAGE,i);
                                try{
                                    new UseUser().SetUser(us);
                                }catch(IOException e){
                                    System.out.println(e.getMessage());}
                                dispose();
                                new MenuMain().Call(us);
                            }else{
                                ImageIcon i = new ImageIcon(this.getClass().getResource("/Imagen/Back.jpg"));
                                JOptionPane.showMessageDialog(null,"Bienvenido","Welcome",JOptionPane.INFORMATION_MESSAGE,i);
                                try{
                                    new UseUser().SetUser(us);
                                }catch(IOException e){
                                    System.out.println(e.getMessage());}
                                dispose();                                
                                new MenuEmpleado().Call(us);                                
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Password Incorrecto");
                            Pass.requestFocus();
                            Pass.selectAll();
                        }
                    }                    
                }
            }
        }else{
            if(!(Name.getText().equals("") && Pass.getText().equals(""))){
                s.setName(Name.getText());
                s.setPassword(Pass.getText());                
                Conectar c = new Conectar();
                c.InsertarUs(s);
                dispose();
                new MenuMain().Call();
            }else{
                JOptionPane.showMessageDialog(null,"Debe de llenar todos los campos");
            }
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void Change1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Change1MouseClicked
        // TODO add your handling code here:
        final ImageIcon im = new ImageIcon(this.getClass().getResource("/Imagen/Usuario.png"));
        JOptionPane.showMessageDialog(null,"Pongase en contacto con Jonathan Gonzalez\n"
            + "jonagonzalez12797@yahoo.es","Forget the Password",JOptionPane.INFORMATION_MESSAGE,im);
        
    }//GEN-LAST:event_Change1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                users = new Conectar().ConexionUs();
                if(users.isEmpty()){
                    Chang1.setText("Nuevo Usuario Administrador");
                    Cursor c = new Cursor(Cursor.DEFAULT_CURSOR);
                    Chang1.setCursor(c);
                    flag = false;
                    Change1.setVisible(false);
                }else{
                    Chang1.setVisible(false);
                    Change1.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private static javax.swing.JLabel Chang1;
    private static javax.swing.JLabel Change1;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    static boolean  flag = true;
    static List<Usuario> users;    
}