/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Items.Comparar;
import Items.Conectar;
import Pojo.Producto;
import Pojo.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author h p
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        setIconImage(new ImageIcon(this.getClass().getResource("/Imagen/capsule.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Campo = new javax.swing.JTextField(8);
        Search = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(Lista);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Aceptar.setText("Modificar");
        Aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel6.add(Aceptar);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Buscar por Nombre:");
        jPanel3.add(jLabel1);
        jPanel3.add(Campo);

        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel3.add(Search);

        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel3.add(Clear);

        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel3.add(Exit);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(464, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    List<Producto> productos;
    List<Usuario> usuarios;
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        if(s.equalsIgnoreCase("Producto")){
            productos = new ArrayList<>();
            int cont = 0;
            List<Producto> prod = new ArrayList<>();
            prod = new Conectar().ConexionProd();
            String s = Campo.getText();
            String id;
            dlm = new DefaultListModel();
            boolean b = false;
            for(Producto p : prod){
                Producto pd = new Producto();
                pd = new Comparar().CompararAll(p, s);
                if(pd == null){
                    cont++;
                }else{
                    String s1 = "Id: "+(id = new Search().SetLength(""+pd.getId()))+", Nombre: "+pd.getName()+","
                            + " Marca: "+pd.getMarca();
                    productos.add(pd);                
                    dlm.addElement(s1);
                    Lista.setModel(dlm);
                }
                if(cont == prod.size()){
                    b = true;
                }
            }
            if(b){
                for(Producto p:prod){
                    if(p.getName().equals(Campo.getText())){
                        productos.add(p);
                        dlm = new DefaultListModel();
                        String s1 = "Id: "+(id = new Search().SetLength(""+p.getId()))+", Nombre: "+p.getName()+","
                            + " Marca: "+p.getMarca();
                        dlm.addElement(s1);
                        Lista.setModel(dlm);
                    }
                }
            }
        }else{
            int con = 0;
            usuarios = new ArrayList<>();
            int cont = 0;
            List<Usuario> us = new ArrayList<>();
            us = new Conectar().ConexionUs();
            String s = Campo.getText();
            dlm = new DefaultListModel();
            boolean b = false;
            for(Usuario u:us){
                Usuario user = new Usuario();
                user = new Comparar().CompararAll(u, s);
                if(user == null){
                    cont++;
                }else{
                    String s1 = "Nombre: "+user.getName();
                    usuarios.add(user);                
                    dlm.addElement(s1);
                    Lista.setModel(dlm);
                }
                if(cont == us.size()){
                    b = true;
                }                
            }
            if(b){                
                for(Usuario u : us){
                    if(u.getName().equals(Campo.getText())){
                        usuarios.add(u);
                        dlm = new DefaultListModel();
                        String s1 = "Nombre: "+u.getName();
                        dlm.addElement(s1);
                        Lista.setModel(dlm);
                    }else{
                        con++;
                    }
                }
            }
            if(con == us.size()){
                JOptionPane.showMessageDialog(null,"Usuario no encontrado");
            }                
        }
    }//GEN-LAST:event_SearchActionPerformed
    DefaultListModel dlm;
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Campo.setText("");
        dlm.removeAllElements();
        Lista.setModel(dlm);
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        if(s.equalsIgnoreCase("Producto")){
            dispose();
            new Interfaces.Producto().Call();
        }else{
            dispose();
            new Interfaces.MenuUsuario().Call();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(s.equalsIgnoreCase("Producto")){
            String id;
            if(Aceptar.getText().equals("Modificar")){            
                if(productos.size()!= 0){
                    for(Producto p: productos){
                        String s1 = "Id: "+(id = new Search().SetLength(""+p.getId()))+", Nombre: "+p.getName()+","
                                + " Marca: "+p.getMarca();
                        if(Lista.getSelectedValue().equals(s1)){              
                            new Mod().SetP(p);
                        }
                    }
                }
            }else{            
                if(productos.size()!= 0){
                    for(Producto p: productos){
                        String s1 = "Id: "+(id = new Search().SetLength(""+p.getId()))+", Nombre: "+p.getName()+","
                                + " Marca: "+p.getMarca();
                        if(Lista.getSelectedValue().equals(s1)){              
                            new Conectar().EliminarProd(p);
                        }
                    }
                }
            }
        }else{
            if(Aceptar.getText().equals("Modificar")){
                if(usuarios.size() != 0){
                    for(Usuario u : usuarios){
                        String s1 = "Nombre: "+u.getName();
                        if(Lista.getSelectedValue().equals(s1)){
                            new NewUser().Call("Modificar Usuario","Modificar",u);
                        }
                    }
                }
            }else{
                if(usuarios.size()!=0){
                    for(Usuario u: usuarios){
                        String s1 = "Nombre: "+u.getName();
                        if(Lista.getSelectedValue().equals(s1)){
                            new Conectar().EliminarUs(u);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField Campo;
    private static javax.swing.JButton Clear;
    private static javax.swing.JButton Exit;
    private javax.swing.JList Lista;
    private static javax.swing.JButton Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    String s;
    void Call(String modificar,String Unkwon) {
        s = Unkwon;
        Search.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/search.png")));
        Clear.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Clean.png")));
        Exit.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/exit.png")));
        Aceptar.setText(modificar);
        this.setVisible(true);
        this.setTitle(modificar+" "+Unkwon); 
        Aceptar.setText(modificar);
    }
}
