/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Items.Conectar;
import Items.JPanelColor;
import Pojo.Usuario;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author h p
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        setIconImage(new ImageIcon(this.getClass().getResource("/Imagen/capsule.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1 = new JPanelColor("/Imagen/Fondo.jpg");
        jPanel1.setLayout(new java.awt.BorderLayout());

        ButtonGroup bg = new ButtonGroup();
        jPanel2.setOpaque(false);
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 19, 0, 19, 0, 19, 0, 19, 0, 19, 0, 19, 0};
        jPanel2Layout.rowHeights = new int[] {0, 22, 0, 22, 0, 22, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jPasswordField1, gridBagConstraints);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Administrador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jCheckBox2, gridBagConstraints);

        jLabel1.setText("jLabel1");
        jLabel1.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);

        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Usuario");
        jPanel3.add(Text);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);

        Aceptar.setToolTipText("Aceptar");
        Aceptar.setBorderPainted(false);
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel4.add(Aceptar);

        Clear.setToolTipText("Limpiar");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel4.add(Clear);

        Exit.setToolTipText("Salir");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel4.add(Exit);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Accion();        
    }//GEN-LAST:event_AceptarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        if(s.equals("Nuevo Usuario")){
            dispose();
            new MenuUsuario().Call();
        }else{
            dispose();
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_ClearActionPerformed
    static ButtonGroup bg = new ButtonGroup();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton Aceptar;
    private static javax.swing.JButton Clear;
    private static javax.swing.JButton Exit;
    private javax.swing.JLabel Text;
    private static javax.swing.JCheckBox jCheckBox1;
    private static javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    String s;
    Usuario us;
    void Call(String s,String s1,Usuario us) {
        this.us = us;
        this.s = s;
        Aceptar.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Ok.png")));
        Clear.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Clean.png")));
        Exit.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/exit.png")));
        jCheckBox1.setSelected(true);
        bg.add(jCheckBox1);
        bg.add(jCheckBox2);
        Text.setText(s);       
        this.setTitle(s1);
        if(us != null){
            if(s1.equals("Modificar")){
                jTextField1.setText(us.getName());
                jPasswordField1.setText(us.getPassword());
                if(us.isAdministrador()){
                    jCheckBox1.setSelected(true);
                }else{
                    jCheckBox2.setSelected(true);
                }
            }
        }
        this.setVisible(true);
    }

    private void Accion() {
        if(!(s.equals("Modificar Usuario"))){
            int cont = -1;
            List<Usuario> s = new Conectar().ConexionUs();
            if(!(jTextField1.getText().equals("") && jPasswordField1.getPassword().equals("") && s.isEmpty())){ 
                Usuario p = new Usuario();
                p.setName(jTextField1.getText());
                p.setPassword(new String(jPasswordField1.getPassword()));
                if(jCheckBox1.isSelected()){
                    p.setAdministrador(true);
                    p.setEmpleado(false);
                }else{
                    p.setAdministrador(false);
                    p.setEmpleado(true);
                }                
                new Conectar().InsertarUs(p);
                jTextField1.setText("");
                jPasswordField1.setText("");
            }else if(!(jTextField1.getText().equals("") && jPasswordField1.getPassword().equals("") && (!s.isEmpty()))){
                cont = 0;
                for(Usuario us: s){
                    Usuario p = new Usuario();
                    p.setId(us.getId());
                    p.setName(jTextField1.getText());
                    p.setPassword(new String(jPasswordField1.getPassword()));
                    if(jCheckBox1.isSelected()){
                        p.setAdministrador(true);
                        p.setEmpleado(false);
                    }else{
                        p.setAdministrador(false);
                        p.setEmpleado(true);
                    }
                    if(p.getName().equalsIgnoreCase(us.getName())){
                        cont++;                    
                    }else{
                        new Conectar().InsertarUs(p);
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                    }
                }
                
            }else if(!(jTextField1.getText().equals("") && jPasswordField1.getPassword().equals(""))){
                JOptionPane.showMessageDialog(null,"Debe de llenar los campos1");
            }
            if(cont == s.size()){
                JOptionPane.showMessageDialog(null, "Usuario Existente");
            }
        }else if(s.equals("Modificar Usuario")){
            if(!((jTextField1.getText().equals("")) && (jPasswordField1.getPassword().equals("")))){
                Usuario s = new Usuario();
                if(us != null){
                    s.setId(us.getId());
                }
                s.setName(jTextField1.getText());
                s.setPassword(new String(jPasswordField1.getPassword()));
                if(jCheckBox1.isSelected()){
                    s.setAdministrador(true);
                    s.setEmpleado(false);
                }else{
                    s.setAdministrador(false);
                    s.setEmpleado(true);
                }
                new Conectar().ModificarUs(s);
            }else{
                JOptionPane.showMessageDialog(null, "Debe de llenar los campos");
            }
        }
    }
}
