/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Items.Conectar;
import Items.JPanelColor;
import java.sql.Connection;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author h p
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Productos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ventas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Historico = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Compra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1 = new JPanelColor("/Imagen/Fondo.jpg");
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Menu Reportes");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel3Layout.rowHeights = new int[] {0, 31, 0, 31, 0};
        jPanel3.setLayout(jPanel3Layout);

        Productos.setText("jLabel2");
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(Productos, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Productos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel3, gridBagConstraints);

        Ventas.setText("jLabel4");
        Ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentasMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel3.add(Ventas, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ventas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel6, gridBagConstraints);

        Historico.setText("jLabel8");
        Historico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoricoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel3.add(Historico, gridBagConstraints);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Historico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel10, gridBagConstraints);

        Salir.setText("jLabel11");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel3.add(Salir, gridBagConstraints);

        Compra.setText("jLabel2");
        Compra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompraMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel3.add(Compra, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Compras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel4, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(570, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosMouseClicked
        // TODO add your handling code here:
        Connection c = new Conectar().Conect();
        try{
            String s = System.getProperty("user.dir")+"/src/items/Productos.jasper";
            JasperReport reporte = (JasperReport)JRLoader.loadObject(s);
            JasperPrint p = JasperFillManager.fillReport(reporte, null, c);
            JasperViewer view = new JasperViewer(p,false);
            view.setIconImage(new ImageIcon(this.getClass().getResource("")).getImage());                    
            view.setTitle("Reporte Producto");
            view.setVisible(true);
            view.setExtendedState(MAXIMIZED_BOTH);
        }catch(Exception e){}
    }//GEN-LAST:event_ProductosMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        dispose();
        new MenuMain().Call();
    }//GEN-LAST:event_SalirMouseClicked

    private void VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseClicked
        // TODO add your handling code here:
        Connection c = new Conectar().Conect();
        try{
            String s = System.getProperty("user.dir")+"/src/items/Ventas.jasper";
            JasperReport reporte = (JasperReport)JRLoader.loadObject(s);
            JasperPrint p = JasperFillManager.fillReport(reporte, null, c);
            JasperViewer view = new JasperViewer(p,false);
            view.setIconImage(new ImageIcon(this.getClass().getResource("")).getImage());                    
            view.setTitle("Reporte de Ventas");
            view.setVisible(true);
            view.setExtendedState(MAXIMIZED_BOTH);
        }catch(Exception e){}
    }//GEN-LAST:event_VentasMouseClicked

    private void HistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoricoMouseClicked
        // TODO add your handling code here:
        Connection c = new Conectar().Conect();
        try{
            String s = System.getProperty("user.dir")+"/src/items/Historico.jasper";
            JasperReport reporte = (JasperReport)JRLoader.loadObject(s);
            JasperPrint p = JasperFillManager.fillReport(reporte, null, c);
            JasperViewer view = new JasperViewer(p,false);
            view.setIconImage(new ImageIcon(this.getClass().getResource("")).getImage());                    
            view.setTitle("Reporte Historico");
            view.setVisible(true);
            view.setExtendedState(MAXIMIZED_BOTH);
        }catch(Exception e){}
    }//GEN-LAST:event_HistoricoMouseClicked

    private void CompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompraMouseClicked
        // TODO add your handling code here:
        Connection c = new Conectar().Conect();
        try{
            String s = System.getProperty("user.dir")+"/src/items/Compra.jasper";
            JasperReport reporte = (JasperReport)JRLoader.loadObject(s);
            JasperPrint p = JasperFillManager.fillReport(reporte, null, c);
            JasperViewer view = new JasperViewer(p,false);
            view.setIconImage(new ImageIcon(this.getClass().getResource("")).getImage());                    
            view.setTitle("Reporte de Compras");
            view.setVisible(true);
            view.setExtendedState(MAXIMIZED_BOTH);
        }catch(Exception e){}
    }//GEN-LAST:event_CompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Compra;
    private static javax.swing.JLabel Historico;
    private static javax.swing.JLabel Productos;
    private static javax.swing.JLabel Salir;
    private static javax.swing.JLabel Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    void Call() {
        Productos.setText("");
        Productos.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Cajas.png")));
        Salir.setText("");
        Salir.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Salir.png")));
        Ventas.setText("");
        Ventas.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Shop.png")));
        Historico.setText("");
        Historico.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Remover.png")));
        Compra.setText("");
        Compra.setIcon(new ImageIcon(this.getClass().getResource("/Imagen/Buy.png")));
        this.setVisible(true);
    }
}
