/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Items.Conectar;
import Pojo.Producto;
import java.awt.Cursor;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author h p
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }
    private List<Producto> prod;
    private DefaultTableModel dtm = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Seleccion = new javax.swing.JComboBox();
        Campo1 = new javax.swing.JTextField(8);
        Search = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Busqueda por:");
        jPanel2.add(jLabel1);

        Seleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Seleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seleccion.removeAllItems();
        String [] busqueda = {"Id","Nombre","Marca"};
        for(String s: busqueda){
            Seleccion.addItem(s);
        }
        Seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionActionPerformed(evt);
            }
        });
        jPanel2.add(Seleccion);

        Campo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Campo1FocusLost(evt);
            }
        });
        Campo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Campo1KeyTyped(evt);
            }
        });
        jPanel2.add(Campo1);

        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel2.add(Search);

        Clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CleanMouseEntered(evt);
            }
        });
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });
        jPanel2.add(Clean);

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel2.add(Exit);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
            },
            new String [] {
                "Id", "Nombre", "Marca", "Cantidad","Precio"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        Area.setEditable(false);
        Area.setColumns(20);
        Area.setRows(5);
        Area.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        Area.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Area.setFocusable(false);
        jScrollPane1.setViewportView(Area);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(459, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        // TODO add your handling code here:
        Search.setToolTipText("Buscar");
    }//GEN-LAST:event_SearchMouseEntered

    private void SeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionActionPerformed
        // TODO add your handling code here:     
        if(Seleccion.getSelectedItem().equals("Id")){
            try{
                if(!(Campo1.getText().equals(""))){
                    int x = parseInt(Campo1.getText());
                }
            }catch(NumberFormatException ev){ 
                Campo1.requestFocus();
                Campo1.setText("");
            }
        }
    }//GEN-LAST:event_SeleccionActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String [] col = {"Id","Nombre","Marca","Cantidad","Precio"};
        Object [][] dat = {};
        dtm = new DefaultTableModel(dat,col);
        if(Campo1.getText().equals("")){
            if(Seleccion.getSelectedItem().equals("Id")){
                JOptionPane.showMessageDialog(null,"Debe de insertar el id");
            }else if(Seleccion.getSelectedItem().equals("Nombre")){
                JOptionPane.showMessageDialog(null,"Debe de insertar el id");
            }else if(Seleccion.getSelectedItem().equals("Marca")){
                JOptionPane.showMessageDialog(null,"Debe de insertar el id");
            }
        }else{ 
            int cont = 0;
            prod = new Conectar().ConexionProd();
            if(Seleccion.getSelectedItem().equals("Id")){
                String x = Campo1.getText();
                String y = SetLength(x); 
                for(Producto p: prod){
                    String l = ""+p.getId();
                    l = SetLength(l);
                    if(l.equals(y)){
                        Object [] newRow = {l,p.getName(),p.getMarca(),p.getCantidad(),p.getPrecio()};
                        dtm.addRow(newRow);
                        jTable1.setModel(dtm);
                        Area.setText(p.getDescripcion()+"\n");
                    }else{
                        cont++;
                    }
                    if(cont == prod.size()){
                        JOptionPane.showMessageDialog(null,"No se encontro el producto deseado");
                        cont = 0;
                    }
                }
            }else if(Seleccion.getSelectedItem().equals("Nombre")){
                for(Producto p: prod){
                    if(p.getName().equals(Campo1.getText())){
                        String s;                        
                        Object [] newRow = {(s=SetLength(""+p.getId())),p.getName(),p.getMarca(),p.getCantidad(),p.getPrecio()};
                        dtm.addRow(newRow);
                        jTable1.setModel(dtm);
                        Area.setText(p.getDescripcion()+"\n");
                    }else{
                        cont++;
                    }
                    if(cont == prod.size()){
                        JOptionPane.showMessageDialog(null,"No se encontro el producto deseado");
                        cont = 0;
                    }
                }
            }else if(Seleccion.getSelectedItem().equals("Marca")){
                for(Producto p: prod){
                    if(p.getMarca().equals(Campo1.getText())){
                        String s;                        
                        Object [] newRow = {(s=SetLength(""+p.getId())),p.getName(),p.getMarca(),p.getCantidad(),p.getPrecio()};
                        dtm.addRow(newRow);
                        jTable1.setModel(dtm);
                        Area.setText(p.getDescripcion()+"\n");
                    }else{
                        cont++;
                    }
                    if(cont == prod.size()){
                        JOptionPane.showMessageDialog(null,"No se encontro el producto deseado");
                        cont = 0;
                    }
                }
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
            },
            new String [] {
                "Id", "Nombre", "Marca", "Cantidad","Precio"
            }
        ));
        Campo1.setText("");
        Area.setText("");
    }//GEN-LAST:event_CleanActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void CleanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CleanMouseEntered
        // TODO add your handling code here:
        Clean.setToolTipText("Limpiar Campos");
    }//GEN-LAST:event_CleanMouseEntered

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        Exit.setToolTipText("Atras");
    }//GEN-LAST:event_ExitMouseEntered

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseClicked

    private void Campo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo1KeyTyped
        // TODO add your handling code here:
        if(Seleccion.getSelectedItem().equals("Id")){
            char car = evt.getKeyChar();
            if((car<'0' || car>'9')) 
                evt.consume();
        }
    }//GEN-LAST:event_Campo1KeyTyped

    private void Campo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Campo1FocusLost
        // TODO add your handling code here:
        if(!(Seleccion.getSelectedItem().equals("Id"))){
            
        }
    }//GEN-LAST:event_Campo1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
                ImageIcon im = new ImageIcon(this.getClass().getResource("/Imagen/search.png"));
                ImageIcon im1 = new ImageIcon(this.getClass().getResource("/Imagen/Clean.png"));
                ImageIcon im2 = new ImageIcon(this.getClass().getResource("/Imagen/exit.png"));
                Search.setIcon(im);
                Clean.setIcon(im1);
                Exit.setIcon(im2);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JTextField Campo1;
    private static javax.swing.JButton Clean;
    private static javax.swing.JButton Exit;
    private static javax.swing.JButton Search;
    private javax.swing.JComboBox Seleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    public String SetLength(String x){
        String y = null;
        if(x.length()==1){
            y = "00000"+x;
        }else if(x.length()==2){
            y = "0000"+x;
        }else if(x.length()==3){
            y = "000"+x;
        }else if(x.length()==4){
            y = "00"+x;
        }else if(x.length()==5){
            y = "0"+x;
        }else if(x.length()==6){
            y = ""+x;
        }          
        return y;
    }
}
